apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-postgres-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-postgres
    spec:
      containers:
        - name: springboot-postgres-k8s
          image: vsharma1985/springboot-pgdb-k8s:springboot-pgdb-k8s
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: SPRING_DATASOURCE_USERNAME  # Setting Database name from configMap
              value: postgres
            - name: SPRING_DATASOURCE_URL  # Setting Database username from Secret
              value: jdbc:postgresql://postgresql:5432/booked?useSSL=false
            - name: SPRING_DATASOURCE_PASSWORD # Setting Database password from Secret
              value: postgres

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-postgres-svc
spec:
  selector:
    app: springboot-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
