apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS book_tbl (
        Id int NOT NULL,
        name varchar(40) NOT NULL,
        
    );

    INSERT INTO customers VALUES (1,'Welcome to K8s deployment');
    